recipe: default.v1
language: vi
pipeline:
- name: WhitespaceTokenizer
  tokenizer: underthesea
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

- name: fasttext_featurizer.FastTextFeaturizer
  cache_path: fasttext/cc.vi.300.bin

- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  model_confidence: softmax

- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
  model_confidence: softmax
- name: FallbackClassifier
  threshold: 0.7
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
  model_confidence: softmax
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
assistant_id: 20230327-112200-future-stunt
